### ISSUE TITLE
Keine Einstellungen im Modul (Contao 4.4.14)

### ISSUE THREAD

**Issue by operatorone** [mindbird/contao-uitotop#1]
Hi, nach der Installation sehe ich im Modul keinerlei Möglichkeiten etwas einzustellen. Ich kann nur das Modul anlegen und speichern.

[https://ibb.co/cyXMSc](url)

**Comment by Wusch** [comment]
Version 2.0 sollte unter Contao 4 funktionieren.

**Comment by operatorone** [comment]
Superklasse! Danke für den schnellen Fix
